#!/usr/bin/env node
// JSON Schema → Zod codegen for lacing body schemas.
//
// Reads `lacing/schema/index.json` from the lacing Python repo (committed
// artifacts), then runs `json-schema-to-zod` over every entry to produce
// `src/types/generated/<name>__v<N>.ts`.
//
// Envelope types (RationalTime, TimeInterval, Reference, Provenance) are
// hand-written in src/domain/envelope.ts per the Phase 3 plan — they don't
// change often and we want explicit control over the wire boundary.
//
// The schema dir defaults to the sibling lacing checkout (relative path), but
// can be overridden with the LACING_SCHEMA_DIR env var — CI uses this to point
// at a fresh checkout of the lacing repo.

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const SCHEMA_DIR = process.env.LACING_SCHEMA_DIR
  ? resolve(process.env.LACING_SCHEMA_DIR)
  : resolve(REPO_ROOT, '../../t/lacing/lacing/schema');
const OUT_DIR = resolve(REPO_ROOT, 'src/types/generated');

function fail(msg) {
  console.error(`codegen: ${msg}`);
  process.exit(1);
}

if (!existsSync(SCHEMA_DIR)) {
  fail(
    `lacing JSON Schema dir not found at ${SCHEMA_DIR}. ` +
      `Point LACING_SCHEMA_DIR at the lacing repo's lacing/schema dir, or ` +
      `regenerate it via:\n  cd ../../t/lacing && python -c "import lacing.bodies; from lacing.schema import export_json_schemas; export_json_schemas('lacing/schema/')"`,
  );
}

const indexPath = join(SCHEMA_DIR, 'index.json');
if (!existsSync(indexPath)) {
  fail(`expected ${indexPath} (set include_meta=True when exporting).`);
}

const index = JSON.parse(readFileSync(indexPath, 'utf8'));

if (existsSync(OUT_DIR)) {
  rmSync(OUT_DIR, { recursive: true });
}
mkdirSync(OUT_DIR, { recursive: true });

const exportedNames = [];

for (const [uri, meta] of Object.entries(index)) {
  const inputPath = join(SCHEMA_DIR, meta.path);
  const safeName = `${meta.name.replace(/-/g, '_')}__v${meta.version}`;
  const outputPath = join(OUT_DIR, `${safeName}.ts`);

  // json-schema-to-zod CLI: -i input -o output -n exportedName -t (TS-only)
  const exportName = `${camelize(meta.name)}V${meta.version}Schema`;
  execSync(
    `npx --yes json-schema-to-zod -i "${inputPath}" -o "${outputPath}" -n ${exportName}`,
    { stdio: 'inherit' },
  );

  exportedNames.push({ uri, name: meta.name, version: meta.version, exportName, file: safeName });
}

// Index file: lookup by URI → schema, plus a tagged union of all bodies.
const lines = [
  '// Generated by scripts/codegen.mjs from lacing/schema/. Do not edit by hand.',
  '// Run `npm run codegen` after the upstream Pydantic models change.',
  '',
];
for (const e of exportedNames) {
  lines.push(`import { ${e.exportName} } from './${e.file}';`);
}
lines.push('', 'export const bodySchemas = {');
for (const e of exportedNames) {
  lines.push(`  '${e.uri}': ${e.exportName},`);
}
lines.push('} as const;', '');
lines.push('export type BodySchemaUri = keyof typeof bodySchemas;', '');
for (const e of exportedNames) {
  lines.push(`export { ${e.exportName} } from './${e.file}';`);
}
writeFileSync(join(OUT_DIR, 'index.ts'), `${lines.join('\n')}\n`);

console.log(`codegen: wrote ${exportedNames.length} schema file(s) to ${OUT_DIR}`);

function camelize(kebab) {
  return kebab
    .split('-')
    .map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1)))
    .join('');
}
